FROM ubuntu 

RUN apt update && apt install libc-dev gcc curl -y

RUN curl https://raw.githubusercontent.com/cd-c89/sysinc/refs/heads/main/shainc/tester.sh -o tester.sh

COPY shainc.c .
COPY rounds.c .
