FROM alpine 

RUN apk add build-base gcc curl python3

RUN curl https://raw.githubusercontent.com/cd-c89/sysinc/refs/heads/main/4096_t/4096_t.h -o 4096_t.h

COPY 4096_t.c .
COPY tester.c .
COPY tester.py .
